name:                Fush
version:             0.1.0.0
github:              "yamagn/Fush"
license:             BSD3
author:              "yamagn"
maintainer:          "syankenpon@gmail.com"
copyright:           "yamagn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yamagn/Fush#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Fush-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Fush

tests:
  Fush-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Fush
