library:
  source-dirs: src
tests:
  Fush-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Fush
copyright: yamagn
maintainer: syankenpon@gmail.com
dependencies:
- unix
- base >= 4.7 && < 5
name: Fush
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: yamagn
github: yamagn/Fush
license: BSD3
executables:
  Fush-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Fush
description: Please see the README on GitHub at <https://github.com/yamagn/Fush#readme>
